CREATE TABLE Medico (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  documento VARCHAR(255) NOT NULL,
  telefono VARCHAR(10) NOT NULL,
  especialidad VARCHAR(255) NOT NULL,
  calle VARCHAR(255) NOT NULL,
  numero VARCHAR(255) NOT NULL,
  ciudad VARCHAR(255) NOT NULL,
  codigo_postal VARCHAR(255) NOT NULL
);
